import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
   createIdempotencyStore,
   markProcessed,
} from '../src/node/lib/idempotencyStore';

type PlanStep = {
   id: string;
   purpose: string;
   dependsOn: string[];
   tool: string;
   parameters: Record<string, unknown>;
};

type PlanState = {
   conversationId: string;
   userId: string;
   plan: PlanStep[];
   final_answer_synthesis_required: boolean;
   stepIndex: number;
   results: Array<{ tool: string; result: unknown }>;
   planCompletedEmitted: boolean;
   status: 'RUNNING' | 'COMPLETED' | 'FAILED';
};

type ConversationEvent = {
   conversationId: string;
   userId: string;
   timestamp: string;
   eventType: string;
   payload: Record<string, unknown>;
};

const lines: string[] = [];

const log = (line: string) => {
   lines.push(line);
};

const resolvePlaceholders = (
   params: Record<string, unknown>,
   results: PlanState['results']
) => {
   const replace = (value: unknown): unknown => {
      if (typeof value === 'string') {
         return value.replace(/<result_from_tool_(\d+)>/g, (_match, index) => {
            const result = results[Number(index) - 1];
            if (!result) return '';
            const output = result.result as
               | { data?: unknown; text?: unknown; rate?: unknown }
               | string
               | Record<string, unknown>;
            if (typeof output === 'string') return output;
            if (output && typeof output === 'object' && 'data' in output) {
               return String(output.data ?? '');
            }
            if (output && typeof output === 'object' && 'rate' in output) {
               return String(output.rate ?? '');
            }
            if (output && typeof output === 'object' && 'text' in output) {
               return String(output.text ?? '');
            }
            return JSON.stringify(output ?? {});
         });
      }
      if (Array.isArray(value)) return value.map(replace);
      if (value && typeof value === 'object') {
         return Object.fromEntries(
            Object.entries(value).map(([key, nested]) => [key, replace(nested)])
         );
      }
      return value;
   };

   return replace(params) as Record<string, unknown>;
};

const applyEvent = (
   state: Map<string, PlanState>,
   event: ConversationEvent
) => {
   if (event.eventType === 'PlanGenerated') {
      state.set(event.conversationId, {
         conversationId: event.conversationId,
         userId: event.userId,
         plan: (event.payload.plan ?? []) as PlanStep[],
         final_answer_synthesis_required: Boolean(
            event.payload.final_answer_synthesis_required
         ),
         stepIndex: 0,
         results: [],
         planCompletedEmitted: false,
         status: 'RUNNING',
      });
      return;
   }

   const current = state.get(event.conversationId);
   if (!current) return;

   if (event.eventType === 'ToolInvocationResulted') {
      const stepIndex = Number(event.payload.stepIndex);
      if (!current.results[stepIndex]) {
         current.results[stepIndex] = {
            tool: String(event.payload.tool ?? ''),
            result: event.payload.result,
         };
      }
      current.stepIndex = Math.max(current.stepIndex, stepIndex + 1);
      if (current.stepIndex >= current.plan.length)
         current.status = 'COMPLETED';
      return;
   }

   if (event.eventType === 'PlanCompleted') {
      current.planCompletedEmitted = true;
      current.status = 'COMPLETED';
   }
};

const nextTransition = (state: PlanState) => {
   if (!state.planCompletedEmitted && state.stepIndex >= state.plan.length) {
      return {
         kind: 'PlanCompleted',
         payload: {
            final_answer_synthesis_required:
               state.final_answer_synthesis_required,
         },
      };
   }
   if (state.status === 'RUNNING' && state.stepIndex < state.plan.length) {
      const step = state.plan[state.stepIndex];
      return {
         kind: 'ToolInvocationRequested',
         payload: {
            invocationId: `${state.conversationId}-${state.stepIndex}`,
            tool: step.tool,
            stepIndex: state.stepIndex,
            parameters: resolvePlaceholders(step.parameters, state.results),
         },
      };
   }
   return null;
};

const now = () => new Date().toISOString();

log('RESILIENCE LOG');
log('Generated by scripts/generate_resilience_log.ts');
log(`Generated at: ${now()}`);
log('');

log('==================================================');
log('Drill 1: Worker Pause + Recovery');
log('==================================================');
{
   const conversationId = 'worker-recovery-local-demo';
   const state = new Map<string, PlanState>();
   applyEvent(state, {
      conversationId,
      userId: 'local-demo-user',
      timestamp: now(),
      eventType: 'PlanGenerated',
      payload: {
         plan: [
            {
               id: 'step_1',
               purpose: 'Compute the requested expression',
               dependsOn: [],
               tool: 'calculateMath',
               parameters: { expression: '6 + 6' },
            },
         ],
         final_answer_synthesis_required: false,
      },
   });
   const initial = nextTransition(state.get(conversationId)!);
   log(`conversationId=${conversationId}`);
   log(
      `while worker paused -> ${initial?.kind} stepIndex=0 tool=calculateMath`
   );
   log('observed: no ToolInvocationResulted while worker is unavailable');
   applyEvent(state, {
      conversationId,
      userId: 'local-demo-user',
      timestamp: now(),
      eventType: 'ToolInvocationResulted',
      payload: {
         invocationId: `${conversationId}-0`,
         tool: 'calculateMath',
         stepIndex: 0,
         result: { text: 'התוצאה היא 12', data: 12 },
      },
   });
   const completed = nextTransition(state.get(conversationId)!);
   log(
      'after worker recovery -> ToolInvocationResulted stepIndex=0 tool=calculateMath'
   );
   log(`next transition -> ${completed?.kind}`);
   log('result: in-flight conversation continues without creating a new plan');
}
log('');

log('==================================================');
log('Drill 2: Orchestrator Crash + Replay Recovery');
log('==================================================');
{
   const conversationId = 'orchestrator-recovery-local-demo';
   const eventLog: ConversationEvent[] = [
      {
         conversationId,
         userId: 'local-demo-user',
         timestamp: now(),
         eventType: 'PlanGenerated',
         payload: {
            plan: [
               {
                  id: 'step_1',
                  purpose: 'Compute the base value',
                  dependsOn: [],
                  tool: 'calculateMath',
                  parameters: { expression: '2 + 2' },
               },
               {
                  id: 'step_2',
                  purpose: 'Multiply the prior result',
                  dependsOn: ['step_1'],
                  tool: 'calculateMath',
                  parameters: { expression: '<result_from_tool_1> * 3' },
               },
            ],
            final_answer_synthesis_required: false,
         },
      },
      {
         conversationId,
         userId: 'local-demo-user',
         timestamp: now(),
         eventType: 'ToolInvocationResulted',
         payload: {
            invocationId: `${conversationId}-0`,
            tool: 'calculateMath',
            stepIndex: 0,
            result: { text: 'התוצאה היא 4', data: 4 },
         },
      },
   ];

   const beforeCrash = new Map<string, PlanState>();
   applyEvent(beforeCrash, eventLog[0]!);
   const step0 = nextTransition(beforeCrash.get(conversationId)!);
   log(`conversationId=${conversationId}`);
   log(
      `before crash -> ${step0?.kind} stepIndex=0 tool=calculateMath parameters=${JSON.stringify(step0?.payload.parameters)}`
   );
   log('orchestrator stops after emitting step 0 request');
   log(
      'tool result lands in the immutable event log while orchestrator is down'
   );

   const replayed = new Map<string, PlanState>();
   for (const event of eventLog) applyEvent(replayed, event);
   const recovered = nextTransition(replayed.get(conversationId)!);
   log(
      `after replay -> ${recovered?.kind} stepIndex=1 tool=calculateMath parameters=${JSON.stringify(recovered?.payload.parameters)}`
   );
   log(
      'result: replay reconstructs state and emits only the missing next transition'
   );
}
log('');

log('==================================================');
log('Drill 3: Duplicate Invocation Handling');
log('==================================================');
{
   const tempDir = mkdtempSync(path.join(os.tmpdir(), 'chatbot-idempotency-'));
   try {
      const store = createIdempotencyStore(tempDir);
      const invocationId = 'duplicate-local-demo';
      const firstSeen = await store
         .get(invocationId)
         .then(() => true)
         .catch(() => false);
      if (!firstSeen) {
         await markProcessed(store, invocationId);
         log(`first delivery -> processed invocationId=${invocationId}`);
      }
      const duplicateSeen = await store
         .get(invocationId)
         .then(() => true)
         .catch(() => false);
      log(
         duplicateSeen
            ? `duplicate delivery -> ignored invocationId=${invocationId}`
            : `duplicate delivery -> ERROR invocationId=${invocationId}`
      );
      log(
         'result: only one ToolInvocationResulted would be emitted for the duplicate key'
      );
      await store.close();
   } finally {
      rmSync(tempDir, { recursive: true, force: true });
   }
}

console.log(lines.join('\n'));
